setwd("~/Documents/GitHub/BioinfGroupProject/rank_cluster_2/k6/analysis/interaction")

get_ol = function(c_clus, compare, s_clus, sets, core = T){
  cmp = read.csv(paste(c_clus,'/', compare, ".tsv", sep = ""), sep = "\t")
  if(core == T){cmp = cmp[cmp[,"CORE.ENRICHMENT"]=="Yes",]}
  
  lst = list()
  for(set in sets){
    current = read.csv(paste(s_clus,'/', set,".tsv", sep = ""), sep="\t")
    if(core == T){current = current[current[,"CORE.ENRICHMENT"]=="Yes",]}
    lst[set] = ifelse(length(current$SYMBOL[current$SYMBOL %in% cmp$SYMBOL]) > 0 , list(current$SYMBOL[current$SYMBOL %in% cmp$SYMBOL]), NA)
  }
  return(lst)
}


#Overlap C2 & C4
get_ol('C2_COVID_PPI', "SARS CORONAVIRUS NSP3-PP1A FROM VIRUS-HOST PPI P-HIPSTER 2020",
       "C2_Hall", "HALLMARK_PI3K_AKT_MTOR_SIGNALING")

get_ol('C2_COVID_PPI', "SARS CORONAVIRUS ORF1AB FROM VIRUS-HOST PPI P-HIPSTER 2020",
       "C2_Hall", "HALLMARK_PI3K_AKT_MTOR_SIGNALING")

get_ol('C4_COVID_PPI', "SARS CORONAVIRUS NSP3-PP1A FROM VIRUS-HOST PPI P-HIPSTER 2020",
       "C4_Hall", "HALLMARK_PI3K_AKT_MTOR_SIGNALING")

get_ol('C4_COVID_PPI', "SARS CORONAVIRUS ORF1AB FROM VIRUS-HOST PPI P-HIPSTER 2020",
       "C4_Hall", "HALLMARK_PI3K_AKT_MTOR_SIGNALING")




#c2 unique
hall2 = c("HALLMARK_DNA_REPAIR","HALLMARK_MITOTIC_SPINDLE")

get_ol('C2_COVID_PPI', "SARS CORONAVIRUS NUCLEOCAPSID PROTEIN FROM VIRUS-HOST PPI P-HIPSTER 2020",
       'C2_Hall', hall2)

get_ol('C2_COVID_PPI', "SARS CORONAVIRUS NSP4-PP1A FROM VIRUS-HOST PPI P-HIPSTER 2020",
       'C2_Hall', hall2)

get_ol('C2_COVID_PPI', "SARS CORONAVIRUS NSP7-PP1A FROM VIRUS-HOST PPI P-HIPSTER 2020",
       'C2_Hall', hall2)

get_ol('C2_COVID_PPI', "SARS CORONAVIRUS HYPOTHETICAL PROTEIN SARS7A FROM VIRUS-HOST PPI P-HIPSTER 2020",
       'C2_Hall', hall2)


#c4 unique
hall4 = c("HALLMARK_APICAL_JUNCTION","HALLMARK_IL2_STAT5_SIGNALING","HALLMARK_COMPLEMENT","HALLMARK_TGF_BETA_SIGNALING",
          "HALLMARK_P53_PATHWAY","HALLMARK_ADIPOGENESIS","HALLMARK_HEME_METABOLISM","HALLMARK_MYOGENESIS",
          "HALLMARK_INFLAMMATORY_RESPONSE","HALLMARK_HYPOXIA","HALLMARK_ALLOGRAFT_REJECTION","HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY",
          "HALLMARK_ESTROGEN_RESPONSE_EARLY","HALLMARK_APOPTOSIS","HALLMARK_INTERFERON_GAMMA_RESPONSE","HALLMARK_NOTCH_SIGNALING",
          "HALLMARK_KRAS_SIGNALING_UP","HALLMARK_IL6_JAK_STAT3_SIGNALING","HALLMARK_COAGULATION","HALLMARK_TNFA_SIGNALING_VIA_NFKB",
          "HALLMARK_BILE_ACID_METABOLISM","HALLMARK_UV_RESPONSE_DN","HALLMARK_INTERFERON_ALPHA_RESPONSE",
          "HALLMARK_WNT_BETA_CATENIN_SIGNALING","HALLMARK_ANDROGEN_RESPONSE","HALLMARK_ESTROGEN_RESPONSE_LATE")  

get_ol('C4_COVID_PPI', "SARS CORONAVIRUS E2 GLYCOPROTEIN PRECURSOR FROM VIRUS-HOST PPI P-HIPSTER 2020",
       'C4_Hall', hall4)

get_ol('C4_COVID_PPI', "SARS CORONAVIRUS NSP8-PP1A FROM VIRUS-HOST PPI P-HIPSTER 2020",
       'C4_Hall', hall4)


#c6 unique
hall6 = c("HALLMARK_MYC_TARGETS_V1","HALLMARK_MYC_TARGETS_V2","HALLMARK_G2M_CHECKPOINT","HALLMARK_E2F_TARGETS")

get_ol('C6_COVID_PPI', "COVID19-NSP8 PROTEIN HOST PPI FROM KROGAN",
       'C6_Hall', hall6)





